networks:
  frontend: null
services:
  web:
    build: .
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    env_file:
    - .env
    image: mywebapp_after
    networks:
    - frontend
    ports:
    - 127.0.0.1:15001:5000
    read_only: true
    security_opt:
    - no-new-privileges:true
    user: 1001:1001
