services:
  web:
    build: .
    image: mywebapp_after
    ports:
      - "127.0.0.1:15001:5000"
    env_file:
      - .env
    read_only: true
    security_opt:
      - no-new-privileges:true
    mem_limit: 256m
    pids_limit: 100
    networks:
      - frontend
  
networks:
  frontend: